apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: celerity-home
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  storage-root: {{ .Values.storageRoot | quote }}
