apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: celerity-home
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: Periodic
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName | quote }}
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/name: celerity-home
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/managed-by: external-secrets
  data:
    - secretKey: token
      remoteRef:
        key: {{ printf "%s/%s" .Values.externalSecrets.itemName .Values.externalSecrets.vehicleTokenProperty | quote }}
    - secretKey: webhook-url
      remoteRef:
        key: {{ printf "%s/%s" .Values.externalSecrets.itemName .Values.externalSecrets.webhookUrlProperty | quote }}
