[package]
name = "control-core"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
celerity-proto = { path = "../celerity-proto" }
control-protocol = { path = "../control-protocol" }
fs4 = "1.1.0"
prost = "0.14.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
toml = "1.1.4"
tract-onnx = "0.23.4"

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
